[package]
name = "ark"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["connect"]

[features]
default = ["release"]
release = ["darkbio-connect/release"]
staging = ["darkbio-connect/staging"]
develop = ["darkbio-connect/develop"]
internal = []

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.60", features = ["derive"] }
darkbio-connect = { path = "connect" }
darkbio-crypto = { version = "0.18.0", features = ["xdsa"] }
hex = "0.4.3"
console = "0.15.11"
