// ark: command line interface for Ark enclaves
// Copyright 2026 Dark Bio AG. All rights reserved.

// Generated by prost-build from wire.proto at build time.
#[allow(dead_code, clippy::all)]
mod inner {
    include!(concat!(env!("OUT_DIR"), "/wire_protocol.rs"));
}
pub use inner::*;
